names = "Adrian Jones <Adrian.Jones@sas.com>; Alex Ge <Alex.Ge@sas.com>; Andrew Christian <Andrew.Christian@sas.com>; Andrew Klitovchenko <andrew.klitovchenko@sas.com>; Andrew Kramer <Andrew.Kramer@sas.com>; Benjamin Sloane <Benjamin.Sloane@sas.com>; Brad Hathaway <Brad.Hathaway@sas.com>; Brian Garrett <Brian.Garrett@sas.com>; Brian Kinnebrew <Brian.Kinnebrew@sas.com>; Brian Rasa <Brian.Rasa@sas.com>; Carlos Lara <Carlos.Lara@sas.com>; Christina Engelhardt <Christina.Engelhardt@sas.com>; Clark Bradley <Clark.Bradley@sas.com>; Clemens Knobloch <Clemens.Knobloch@sas.com>; Craig LeBlanc <Craig.LeBlanc@sas.com>; Cristina Conti <Cristina.Conti@sas.com>; David Burgess <David.Burgess@sas.com>; David Fuentes <David.Fuentes@sas.com>; David Hare <David.Hare@sas.com>; Deepak Ramanathan <Deepak.Ramanathan@sas.com>; Diana Shaw <Diana.Shaw@sas.com>; Evan Guarnaccia <Evan.Guarnaccia@sas.com>; Frédéric Combaneyre <Frederic.Combaneyre@sas.com>; Gregor Herrmann <Gregor.Herrmann@sas.com>; Helmut Plinke <Helmut.Plinke@sas.com>; Ivor Moan <Ivor.Moan@sas.com>; Jacky Long <Jacky.Long@sas.com>; James Kochuba <James.Kochuba@sas.com>; Jason Loh <jason.loh@sas.com>; Jeff Owens <Jeff.Owens@sas.com>; Jeff Stander <Jeff.Stander@sas.com>; Jesse Luebbert <Jesse.Luebbert@sas.com>; Jochen Kirsten <Jochen.Kirsten@sas.com>; Joseph Costin <Joseph.Costin@sas.com>; Juthika Khargharia <Juthika.Khargharia@sas.com>; Kathy Lange <Kathy.Lange@sas.com>; Keith Renison <Keith.Renison@sas.com>; Lai Phong Tran <LaiPhong.Tran@sas.com>; Larry Orimoloye <Larry.Orimoloye@sas.com>; Lisa Dodson <Lisa.Dodson@sas.com>; Lou Galway <Lou.Galway@sas.com>; Marc Wellman <Marc.Wellman@sas.com>; Mary Osborne <Mary.Osborne@sas.com>; Mathias Coopmans <mathias.coopmans@sas.com>; Michael Ingraham <Michael.Ingraham@sas.com>; Muhammad Asif Abbasi <Asif.Abbasi@sas.com>; Pasi Helenius <pasi.helenius@sas.com>; Paul Bachteal <Paul.Bachteal@sas.com>; Paul Gittins <Paul.Gittins@sas.com>; Paul Northrop <Paul.Northrop@sas.com>; Pei Sin Khoo <peisin.khoo@sas.com>; Phil Weiss <Phil.Weiss@sas.com>; Renato Luppi <Renato.Luppi@sas.com>; Roger Shears <roger.shears@sas.com>; Ryan Lolli <Ryan.Lolli@sas.com>; Sascha Schubert <Sascha.Schubert@sas.com>; Scott Chastain <Scott.Chastain@sas.com>; Steve Erwin-Davidson <Steve.Erwin-Davidson@sas.com>; Steve Mellgren <Steve.Mellgren@sas.com>; Steven Sober <Steven.Sober@sas.com>; Tuba Islam <Tuba.Islam@sas.com>; Tyler Freckmann <Tyler.Freckmann@sas.com>; Varsha Chawla <Varsha.Chawla@sas.com>; Wentsau Chiu <Wentsau.Chiu@sas.com>; Yi Jian Ching <YiJian.Ching@sas.com>"
names = names.split(" ")

fout = open('C:/GTP/Programming/roadshow_text/prepped_data/stoplist_gtp.csv', 'w', encoding='utf-8')

for i,name in enumerate(names):
	if i==0:
		fout.write('TERM' + '\n')
	if "<" in name:
		pass
	else:
		print(name)
		fout.write(name + '\n')
